version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-ten
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
    networks:
      - db

networks:
  db:
    driver: bridge